# Generated by Django 3.2 on 2022-12-06 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.IntegerField(default=1, verbose_name='Тип аккаунта'),
        ),
        migrations.AlterField(
            model_name='account',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='credit.client'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=16, verbose_name='Номер аккаунта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_year',
            field=models.DateField(auto_now_add=True, verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='citizenship',
            field=models.CharField(default='Кыргызстан', max_length=20, verbose_name='гражданство'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=20, verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='client',
            name='work_place',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='credit.account'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата получения кредита'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='sum',
            field=models.IntegerField(verbose_name='Сумма кредита'),
        ),
    ]
